backend:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}

fos_user_registration_confirmed:
    path:      /{_locale}/register/confirmed
    defaults:  { _controller: AppBundle:User:afterLogin}


fos_user_security_logout:
    path:      /logout
    defaults:  { _controller: FOSUserBundle:Security:logoutAction}



email:
    path:      /{_locale}/email
    defaults:  { _controller: AppBundle:Default:email}

homepage:
    path:      /{_locale}
    defaults:  { _controller: AppBundle:Default:landingPage, _locale: pt }
#    defaults:  { _controller: AppBundle:Default:index, _locale: pt }
    requirements:
        _locale:  en|pt