admin_criterio_index:
    path:     /
    defaults: { _controller: "AppBundle:Criterio:index" }
    methods:  GET

admin_criterio_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Criterio:show" }
    methods:  GET

admin_criterio_new:
    path:     /new
    defaults: { _controller: "AppBundle:Criterio:new" }
    methods:  [GET, POST]

admin_criterio_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Criterio:edit" }
    methods:  [GET, POST]

admin_criterio_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Criterio:delete" }
    methods:  DELETE
