admin_votacao_index:
    path:     /
    defaults: { _controller: "AppBundle:Votacao:index" }
    methods:  GET

admin_votacao_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Votacao:show" }
    methods:  GET

admin_votacao_new:
    path:     /new/{candidatura}
    defaults: { _controller: "AppBundle:Votacao:new" }
    methods:  [GET, POST]

admin_votacao_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Votacao:edit" }
    methods:  [GET, POST]

admin_votacao_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Votacao:delete" }
    methods:  DELETE



admin_votacao_resultados:
    path:     /resultados
    defaults: { _controller: "AppBundle:Votacao:resultados" }
    methods:  GET